import { Jost } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const jost = Jost({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <body className={jost.className}>
      <Header />
        {children}
      </body>
    </html>
  );
}
